### ISSUE TITLE
Category analytics for the Enterprise platform

### ISSUE THREAD

**Issue by anssip** [flowplayer/analytics-api#2]
The analytics API needs to include category specific analytics.

Is this method enough? https://dweb.flowplayer.com/docs/video-management/analytics-api#popularcategories

**Comment by emanuelflowplayer** [comment]
There should be a basic view in the UI for this so we can start to see how it performs.

**Comment by dwes** [comment]
@anssip We need both displays and liveviews for each category. Would also be good to have the possibility to get analytics summarised per day as in intervals request: https://dweb.flowplayer.com/docs/video-management/analytics-api#intervals
